### ISSUE TITLE
Processing.R mode not detected in contributions manager

### ISSUE THREAD

**Issue by jeremydouglass** [processing-r/Processing.R#254]
## Problem

Currently Processing.R is not showing up in PDE Contributions Manager.

## Reason

This file is missing -- PDE contributions manager doesn't show a listing and doesn't link to the zip file without it.

http://gaocegege.com/Processing.R/RLangMode.txt

## Solution

@gaocegege  do you have a copy of RLangMode.txt ?

If so:

1. attach RangLangeMode.txt to the 1.0.6 release here:

https://github.com/processing-r/Processing.R/releases/edit/v1.0.6

2. I will notify the Processing Foundation to update sources.conf here:

https://raw.githubusercontent.com/processing/processing-docs/master/contrib_generate/sources.conf

from this entry:

220 \ http://gaocegege.com/Processing.R/RLangMode.txt

to this:

220 \ https://github.com/processing-r/Processing.R/releases/download/latest/RLangMode.txt

This is how other github-hosted libraries do it, for example:

https://github.com/gohai/processing-uploadtopi/releases/
https://github.com/gohai/processing-uploadtopi/releases/latest/download/UploadToPiTool.txt

**Comment by jeremydouglass** [comment]
Okay, I added an old copy of the file to the latest release and submitted an update here:

https://github.com/processing/processing-docs/pull/769

If you have a more up-to-date version of the file, please update at https://github.com/processing-r/Processing.R/releases/edit/v1.0.6

**Comment by gaocegege** [comment]
@jeremydouglass Yeah, I will check it. Thanks

**Comment by jeremydouglass** [comment]
Great -- I needed to update the contents of the file (url) too, so I made it a 1.0.7 release.

Our link to "latest" -- "Processing.R/releases/download/latest/RLangMode.txt" -- is now added to PDE Contributions Manager, so the mode is live again in PDE.

However, it currently downloads fully using Contributions Manager and then fails to install with "Error during download and install." My guess is that is because the actual zip attached to the release is currently the 1.0.6 zip, and the PDE installer is failing a version check to match the listing (1.0.7). We can replace it with the correct zip once I set up builds on this computer.

**Comment by gaocegege** [comment]
I think the text file is in docs: https://github.com/processing-r/Processing.R/blob/master/docs/RLangMode.txt

**Comment by jeremydouglass** [comment]
It is installing correctly from PDE Contributions Manager.

However, it lists v1.0.7, but the zip has v1.0.6 in it--it installs, but shows an out-of-date warning in Contributions Manager.

To fix I have rebuilt with deploy.sh and am uploading the matching release zip now.
