### ISSUE TITLE
Update readme.md badge stack

### ISSUE THREAD

**Issue by jeremydouglass** [processing-r/Processing.R#256]
Currently the project readme.md has badges from the GSOC2017 development, before the repo was migrated to processing-r.

This include integration status displays for:

-  appveyor: https://ci.appveyor.com/project/gaocegege/processing-r/branch/master
-  codacy: https://www.codacy.com/app/gaocegege/Processing-R
-  gitter: https://gitter.im/gaocegege/Processing.R
-  shields.io: https://img.shields.io/github/release/gaocegege/Processing.R.svg
-  stackshare: https://stackshare.io/gaocegege/processing-r
-  travis-ci: https://travis-ci.org/gaocegege/Processing.R
-  ...and a docker deprecation badge.

@gaocegege -- we can just taking down the CI -- like travis and appveyor and codacy -- unless you suggest migrating them to processing-r org accounts or to my personal account. What do you recommend? You can also leave the gitter if you prefer to be contacted about the project like that, or we can change it / take it down.

I'm not sure about stackshare or what it is -- should we drop it, migrate it, or leave it?

<p align="center">
    <a href="https://travis-ci.org/gaocegege/Processing.R"><img src="https://travis-ci.org/gaocegege/Processing.R.svg?branch=master" alt="Travis CI"></a>
    <a href="https://ci.appveyor.com/project/gaocegege/processing-r/branch/master"><img src="https://ci.appveyor.com/api/projects/status/9lq6psaw9c18ins8/branch/master?svg=true" alt="appveyor"></a>
    
    <a href="https://www.codacy.com/app/gaocegege/Processing-R?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=gaocegege/Processing.R&amp;utm_campaign=Badge_Grade"><img src="https://api.codacy.com/project/badge/Grade/33ebc49f6f764fffb7ea7bf617edf902" alt="Codacy Badge"></a>
    
    <a href="https://stackshare.io/gaocegege/processing-r"><img src="https://img.shields.io/badge/tech-stack-0690fa.svg?style=flat" alt="StackShare"></a>
    <a href="https://github.com/processing-r/Processing.R/releases"><img src="https://img.shields.io/github/release/gaocegege/Processing.R.svg" alt="GitHub Release"></a>
    <a href="https://gitter.im/gaocegege/Processing.R?utm_source=badge&amp;utm_medium=badge&amp;utm_campaign=pr-badge"><img src="https://badges.gitter.im/gaocegege/Processing.R.svg" alt="Gitter"></a>
    <a href="https://github.com/processing-r/Processing.R/blob/master/raw-docs/devel/compilation.md#docker-image-deprecated"><img src="https://img.shields.io/badge/docker-deprecated-yellowgreen.svg" alt=""></a>
</p>

```
<p align="center">
    <a href="https://travis-ci.org/gaocegege/Processing.R"><img src="https://travis-ci.org/gaocegege/Processing.R.svg?branch=master" alt="Travis CI"></a>
    <a href="https://ci.appveyor.com/project/gaocegege/processing-r/branch/master"><img src="https://ci.appveyor.com/api/projects/status/9lq6psaw9c18ins8/branch/master?svg=true" alt="appveyor"></a>
    <!--<a href="https://quay.io/repository/gaocegege/processing.r"><img src="https://quay.io/repository/gaocegege/processing.r/status" alt="Docker Repository on Quay" title="Docker Repository on Quay"></a>-->
    <a href="https://www.codacy.com/app/gaocegege/Processing-R?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=gaocegege/Processing.R&amp;utm_campaign=Badge_Grade"><img src="https://api.codacy.com/project/badge/Grade/33ebc49f6f764fffb7ea7bf617edf902" alt="Codacy Badge"></a>
    <!--<a href="https://www.codacy.com/app/gaocegege/Processing-R?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=gaocegege/Processing.R&amp;utm_campaign=Badge_Coverage"><img src="https://api.codacy.com/project/badge/Coverage/33ebc49f6f764fffb7ea7bf617edf902" alt="Codacy Badge"></a>-->
    <a href="https://stackshare.io/gaocegege/processing-r"><img src="https://img.shields.io/badge/tech-stack-0690fa.svg?style=flat" alt="StackShare"></a>
    <a href="https://github.com/processing-r/Processing.R/releases"><img src="https://img.shields.io/github/release/gaocegege/Processing.R.svg" alt="GitHub Release"></a>
    <a href="https://gitter.im/gaocegege/Processing.R?utm_source=badge&amp;utm_medium=badge&amp;utm_campaign=pr-badge"><img src="https://badges.gitter.im/gaocegege/Processing.R.svg" alt="Gitter"></a>
    <a href="https://github.com/processing-r/Processing.R/blob/master/raw-docs/devel/compilation.md#docker-image-deprecated"><img src="https://img.shields.io/badge/docker-deprecated-yellowgreen.svg" alt=""></a>
</p>
```

This is a follow-up to #75

**Comment by gaocegege** [comment]
LGTM

**Comment by jeremydouglass** [comment]
> LGTM

Switching:

-  travis, codacy, appveyor

Dropping:

-  shields.io: https://img.shields.io/github/release/gaocegege/Processing.R.svg
-  stackshare: https://stackshare.io/gaocegege/processing-r

I also dropped your gitter. Would you like to leave your gitter, or take it off?

**Comment by gaocegege** [comment]
We can drop shields.io, stackshre and gitter, I think. Thanks
