### ISSUE TITLE
Getting this running with Processing 4.0

### ISSUE THREAD

**Issue by benfry** [processing-r/Processing.R#262]
It looks like this has errors on startup with Processing 4.0 alpha 4, because this code references the `frame` field of `PApplet`. 

The errors seem more or less identical to the issues in Python Mode, both of which seem to be based in part on older (2.x? 3.x?) code copied from the source of processing.core (or maybe this was based on the Python code? I'm not sure). A simple workaround is to use most of these same changes to access the `frame` field by reflection (if you'd like to make the library backwards compatible with 3.x)
https://github.com/benfry/processing.py/commit/87bc9c59fc0039021871c11fce688b1518151db5

That being said, relying on the `frame` object is problematic at best: it only works for AWT, and things like `macosxFullScreenToggle(frame)` shouldn't be necessary (and are unlikely to work anyway) these days.

Hope that helps…

**Comment by jeremydouglass** [comment]
Belated thanks for sharing the explanation and you Python Mode fix, Ben. As soon as possible possible I'll look at applying the same fix and testing on R Mode.

(although anyone wanting to make a pull request in the meantime is welcome!)

Re: the origin of using frame, I *believe* that the code was based on Python Mode, which served as a reference model.

**Comment by benfry** [comment]
Sure thing; the fix should be super simple—the first few lines from that PR—but let me know if you run into trouble.

**Comment by benfry** [comment]
A few updates added: https://github.com/jdf/processing.py/pull/389/files

**Comment by benfry** [comment]
…and a PR https://github.com/processing-r/Processing.R/pull/263

**Comment by jeremydouglass** [comment]
Belated thanks again -- new release v1.0.8 is published with a Processing 4.0 fix. I tested it on Processing 3 and there don't appear to be any regressions. It should get automatically picked up by Processing Contributions Manager sometime soon.

Closed by #263
