### ISSUE TITLE
Transfer the ownership from gaocegege to The Processing Foundation

### ISSUE THREAD

**Issue by gaocegege** [processing-r/Processing.R#75]
I have the idea to transfer the ownership from me to The Processing Foundation, and this issue will be blocked until Evaluation 2 ends. When it ends, we will talk about it.

**Comment by jeremydouglass** [comment]
Let's check in about this during our E2 meeting.

**Comment by gaocegege** [comment]
I think maybe we could wait until the mode is released to PDE.

**Comment by gaocegege** [comment]
Should we talk with the foundation about the issue？
